package com.xuanjian.springboot.pojo.enums;

public enum DomainType {
    BUSINESS_DOMAIN,
    ADVERTISE_DOMAIN,
    RESOURCES_DOMAIN,
    THIRD_PARTY_DOMAIN,
    DISTRIBUTION_DOMAIN,
    BROADCAST_DOMAIN,
    ALTERNATIVE_DOMAIN,
    GRAPH_DIVIDED_DOMAIN,
    PAGE_DOMAIN,
    UPDATE_DOMAIN,
    USER_DOMAIN,
}
